experiment:
  name: "case1"
  description: "Self-training model (STM) per appliance"

data:
  dataset: "refit"
  houses:
    - 2
  appliances:
    - hi-fi
  train_range: ["2014-05-01", "2014-11-01"]
  test_range: ["2015-01-11", "2015-01-20"]
  train_fraction: 1.0
  clear_issues: True

paths:
  appliance_map: "datasets/metadata/refit_appliance_map.json"

