experiment:
  name: "case1"
  description: "Self-training model (STM) per appliance"

data:
  dataset: "refit"
  houses:
    - 9
  appliances:
    - television
  train_range: ["2015-01-01", "2015-07-01"]
  test_range: ["2014-12-01", "2014-12-10"]
  train_fraction: 1.0
  clear_issues: True

paths:
  appliance_map: "datasets/metadata/refit_appliance_map.json"

