data:
  dataset: refit
  houses: [2]
  train_range: ["2014-05-01", "2014-11-01"]
  test_range: ["2015-01-11", "2015-01-20"]
  train_fraction: 1
  clear_issues: True

paths:
  appliance_map: "datasets/metadata/refit_appliance_map.json"