data:
  dataset: refit
  houses: [1]
  train_range: ["2013-01-01", "2013-01-02"]
  test_range: ["2013-10-21", "2013-10-30"]
  train_fraction: 1
  clear_issues: True

paths:
  appliance_map: "datasets/metadata/refit_appliance_map.json"